---
# CRI
container_runtime: docker
docker_version: 18.06.2~ce~3-0~ubuntu

# Kurnetes Components Versions
kubernetes_repo_distribution: 'xenial'
kubelet_version: '1.15.4'
kubectl_version: '1.15.4'
kubeadm_version: '1.15.4'
critools_version: '1.15.0'
#Â critools variables
critools:
  v1.16.0:
    crictl:
      sha256: a3eefa10a483c643ad85aee3d7832a720976ef7e80dde46b212eaaacd7d09512
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
    critest:
      sha256: 909ba3e1404c86b82a957d4c69ae9a40e418a09e104fc017e708b877f78eaa73
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
  v1.17.0:
    crictl:
      sha256: 7b72073797f638f099ed19550d52e9b9067672523fc51b746e65d7aa0bafa414
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
    critest:
      sha256: 17088d99f70f3e03d8215de3594cbec367749b0a187f147cc3b2b975e497b433
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
  v1.18.0:
    crictl:
      sha256: 876dd2b3d0d1c2590371f940fb1bf1fbd5f15aebfbe456703ee465d959700f4a
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
    critest:
      sha256: 23968677bdf5d4055e5118c85449b19b046ee1d8822cae5859b7a4a80c2f1955
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
kubernetescni_version: '0.7.5'
kubernetes_cloud_provider: 'aws'
# Docker Configurations
# registry_mirrors:
# - ""
# docker_dns:
# - ""
